import tensorflow as tf
import numpy as np
from PIL import Image
import io
import os

# --- CONFIGURATION ---
# Point to the NEW trained model
MODEL_PATH = "model/efficientnetv2s_finetuned.keras"

# Load the class names dynamically from the text file generated by training
CLASSES_PATH = "model/classes.txt"

# Default labels in case the file is missing (Fallback)
LABELS = [
    'demodicosis', 
    'dermatitis', 
    'fungal_infection', 
    'healthy', 
    'hypersensitive', 
    'ringworm'
]

# Try to load the actual classes from training
if os.path.exists(CLASSES_PATH):
    with open(CLASSES_PATH, "r") as f:
        LABELS = [line.strip() for line in f.readlines()]
    print(f"✅ Loaded Class Labels: {LABELS}")
else:
    print("⚠️ Warning: classes.txt not found. Using default labels.")

# Load the model
model = None
try:
    model = tf.keras.models.load_model(MODEL_PATH)
    print("✅ Model loaded successfully.")
except Exception as e:
    print(f"❌ Error loading model: {e}")

def predict_disease(image_bytes):
    if model is None:
        return "Model Error", 0.0
    
    # Preprocess
    try:
        image = Image.open(io.BytesIO(image_bytes)).convert('RGB')
        image = image.resize((224, 224)) # EfficientNet Expects 224x224
        img_array = np.array(image)
        img_array = np.expand_dims(img_array, axis=0) # Make batch of 1
        
        # Predict
        predictions = model.predict(img_array)
        
        class_index = np.argmax(predictions[0])
        confidence = np.max(predictions[0])
        
        return LABELS[class_index], confidence
    except Exception as e:
        print(f"Prediction Error: {e}")
        return "Error", 0.0